default_install_hook_types:
  - post-checkout
  - post-merge
  - pre-commit
  - pre-push

default_stages:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: lint
        name: run lint checks
        always_run: true
        entry: make lint
        language: system
        pass_filenames: false

      - id: format-check
        name: check application code formatting
        always_run: true
        entry: make format-check
        language: system
        pass_filenames: false

      - id: test
        name: run automated tests
        always_run: true
        entry: make test
        language: system
        pass_filenames: false
        stages:
          - pre-push

      - id: check-dotenv
        name: compare sample.env to .env
        always_run: true
        entry: make .env
        language: system
        pass_filenames: false
        stages:
          - post-checkout
          - post-merge
