app:
  config:
    id: arti-service
    collect_metrics: False
    log_level: INFO
llm:
  provider: openai
  config:
    model: 'gpt-3.5-turbo-1106'
    temperature: 0.5
    max_tokens: 1000
    top_p: 1
embedder:
  provider: openai
  config:
    vector_dimension: 1536
chunker:
  chunk_size: 2000
  chunk_overlap: 0
  length_function: len
vectordb:
  provider: pinecone  # You must also set PINECONE_API_KEY in your environment
  config:
    metric: cosine
    vector_dimension: 1536
    index_name: main-index
    pod_config:
      environment: gcp-starter
