encryptionsalt: v1:8F/vauKV0CI=:v1:cNX8KusaqrZPtadB:5bhYHxZDmn5DQwE4Ia6lQl2+GiWiWQ==
config:
  arti:appConfigFile: config/deploy.config.yaml
  arti:dataLoadEventRuleSchedule: rate(10 minute)
  arti:dataLoadEventRuleState: ENABLED
  arti:logLevel: DEBUG
  arti:openAiApiKeySecretName: /catmeme/cloud-platform/sandbox/arti/access-token/openai
  arti:pineconeApiKeySecretName: /catmeme/cloud-platform/sandbox/arti/access-token/pinecone
  arti:slackBotTokenSecretName: /catmeme/cloud-platform/sandbox/arti/access-token/slack
  aws:profile: sandbox-deployment
  aws:region: us-east-1
