config:
  aws:profile: sandbox-deployment
  aws:region: us-east-1
  arti:logLevel: DEBUG
  arti:openAiApiKeySecretName: /catmeme/cloud-platform/sandbox/arti/access-token/openai
  arti:slackBotTokenSecretName: /catmeme/cloud-platform/sandbox/arti/access-token/slack
