encryptionsalt: v1:bizuZ7E2T68=:v1:MmtcwcYUnl1UlSZV:qxLP+SjdYG9+YPpsLofIAZT10P9H1w==
config:
  arti:appConfigFile: config/deploy.config.yaml
  arti:dataLoadEventRuleSchedule: rate(30 minutes)
  arti:dataLoadEventRuleState: DISABLED
  arti:logLevel: DEBUG
  arti:openAiApiKeySecretName: /catmeme/cloud-platform/main/arti/access-token/openai
  arti:pineconeApiKeySecretName: /catmeme/cloud-platform/main/arti/access-token/pinecone
  arti:slackBotTokenSecretName: /catmeme/cloud-platform/main/arti/access-token/slack
  arti:sqsMessageTimeout: 7200
  arti:sqsReservedConcurrentExecutions: 10
  aws:profile: main-deployment
  aws:region: us-east-1
